---
title: AMRAP NUTRITION
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: As Many Rounds As Possible AMRAP defines our philosophy Through determination,
  intensity, and focus, we aim to inspire and empower our community Join us!
baseurl: ''
url: https://www.amrapnutrition.com
logo: "/assets/images/amrap-logo.png"
lang: en_US
author: AMRAP Nutrition
twitter:
  username: amrapnutrition
facebook:
  publisher: https://www.facebook.com/AMRAPnutrition
social:
  name: AMRAP NUTRITION
  links:
  - https://twitter.com/amrapnutrition
  - https://www.facebook.com/AMRAPnutrition
  - https://www.youtube.com/user/AMRAPnutrition
  - https://www.instagram.com/amrapnutrition/
webmaster_verifications:
  google: 1234
  bing: 1234
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- ".sass-cache"
- log
- node_modules
- package.json
- package-lock.json
- ".DS_Store"
- ".sass-cache"
- settings.yml
- assets/js
- assets/scss
